### ISSUE TITLE
Crashing on Linux

### ISSUE THREAD

**Issue by devmpv** [UnderwaterApps/overlap2d#134]
Latest jar Overlap2D-0.1.1.jar is crashing on Ubuntu with the following error:
```
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:292)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:377)
	at com.uwsoft.editor.proxy.FontManager.getSystemFontFiles(FontManager.java:88)
	at com.uwsoft.editor.proxy.FontManager.preCacheSystemFontsMap(FontManager.java:95)
	at com.uwsoft.editor.proxy.FontManager.generateFontsMap(FontManager.java:132)
	at com.uwsoft.editor.proxy.FontManager.onRegister(FontManager.java:50)
	at com.puremvc.core.CoreModel.registerProxy(CoreModel.java:113)
	at com.puremvc.patterns.facade.SimpleFacade.registerProxy(SimpleFacade.java:235)
	at com.uwsoft.editor.controller.BootstrapProxyCommand.execute(BootstrapProxyCommand.java:41)
	at com.puremvc.patterns.command.MacroCommand.execute(MacroCommand.java:132)
	at com.puremvc.core.CoreController.executeCommand(CoreController.java:139)
	at com.puremvc.core.CoreController$$Lambda$21/155518574.onNotification(Unknown Source)
	at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
	at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
	at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
	at com.uwsoft.editor.Overlap2DFacade.startup(Overlap2DFacade.java:52)
	at com.uwsoft.editor.Overlap2D.create(Overlap2D.java:69)
```

When running from sources in Eclipse:

```
com.badlogic.gdx.utils.SerializationException: Error reading file: style/uiskin.json
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:97)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:74)
	at com.kotcrab.vis.ui.VisUI.load(VisUI.java:54)
	at com.uwsoft.editor.Overlap2D.create(Overlap2D.java:66)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
	at java.awt.Container.addImpl(Container.java:1119)
	at java.awt.Container.add(Container.java:415)
	at com.badlogic.gdx.backends.lwjgl.LwjglFrame.addCanvas(LwjglFrame.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglFrame$2.run(LwjglFrame.java:96)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: style/uiskin.json
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:683)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:95)
	... 23 more
Caused by: com.badlogic.gdx.utils.SerializationException: Error parsing file: style/uiskin.json
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:681)
	... 24 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: style/uiskin.json (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:163)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
	... 25 more
```

**Comment by azakhary** [comment]
For the eclipse I know that issue is in eclipse itself (it would work great with intellij) eclise is just looking in the wrong folder for some reason (outside of assets).  Now as for jar crashing, I am not sure if I changed anything there, judging by lien number I can say that it looks for fonts on your home director .fonts folder and probably it doesnot exists now that's why it crashes. you sure previous jar works for you now? And can you check if you have that directory?

**Comment by devmpv** [comment]
Ok, regarding jar that was the case (missing .fonts folder). It would be great to let Overlap create that folder or somehow bypass that access if its not present.
Regarding second error - it is happening even with "gradle run" which should not rely on any IDE.
Anyway, thanks for the explanation!

**Comment by azakhary** [comment]
I know this should not rely on IDE, and had the same problem, that I really want to figure out. I am not sure how. but for eclipse things start at root folder. and when it's Intellij they start from assets folder. and I am really not sure how that happens...

**Comment by azakhary** [comment]
When jar is built it works fine though..

**Comment by devmpv** [comment]
I have tried to change the working directory in the launcher with the same result. It helps in other libgdx projects while here it doesn't.
Seems like you have a mix of Idea and Gradle setups which is working ). Are you using Idea to generate jar file? Because jar generated with gradle is not starting because of "no main manifest attribute, in overlap2d-0.1.1.jar".
If we can manage the "gradle jar" to work - then problem with multiplatform will be solved by itself.

**Comment by devmpv** [comment]
Adding following lines to build.gradle leads to correct jar generation:
jar {
    manifest {
        attributes 'Main-Class': 'com.uwsoft.editor.Main'
    }
    from {
    	configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
  	}
}

But.. it fails to start because of the original error. Which gradle run also has. 
Will try to find out

**Comment by azakhary** [comment]
I am generating jar with a linux server running gradle tasks, and it works.

**Comment by azakhary** [comment]
it's just not "jar" but "dist" task.
gradle clean build dist

**Comment by devmpv** [comment]
when i run "gradle clean build dist"
Input file does not exist: /home/myusername/Desktop/art/textures
Could not execute build using Gradle distribution 'http://services.gradle.org/distributions/gradle-2.2-all.zip'.
gradle thinks it is Desktop folder? I'm lost )

**Comment by azakhary** [comment]
o_O that's even weirder.

**Comment by devmpv** [comment]
with paths changed like this "$projectDir/art/textures/" gradle is not giving error, however generated jar is still failing to start

**Comment by azakhary** [comment]
which of the errors are in generated jars stacktrace?

**Comment by devmpv** [comment]
this one "Error reading file: style/uiskin.json"

**Comment by azakhary** [comment]
I can fix that tomorrow, by adding a quick check in code to see if assets folder exists or not in several places. an ok. temp solution. coupled with gradle change, it can make things compile and run for you.

**Comment by felipebueno** [comment]
Hi, @azakhary :)
I want to contribute to Overlap2d and I'm trying to run it from sources with ```./gradlew run```. But it's throwing this ```SerializationException: Error reading file: style/uiskin.json```.

Can you help me with that?

Thanks in advance! :)

ps: You can get the full stacktrace here: http://dontpad.com/overlap2d/SerializationException

**Comment by azakhary** [comment]
It's eclipse?

**Comment by azakhary** [comment]
before doing run, can you run task called "build" first?

**Comment by felipebueno** [comment]
It's IntelliJ... but the same happens running from the command line. I'll try that :)

**Comment by felipebueno** [comment]
hmm it didn't work because some tests fail
```./gradlew build
...
com.commons.O2DDialogTest > shouldAddCloseButton FAILED
    com.badlogic.gdx.utils.SerializationException at O2DDialogTest.java:28
        Caused by: com.badlogic.gdx.utils.SerializationException at O2DDialogTest.java:28
            Caused by: com.badlogic.gdx.utils.SerializationException at O2DDialogTest.java:28
                Caused by: com.badlogic.gdx.utils.GdxRuntimeException at O2DDialogTest.java:28
                    Caused by: com.badlogic.gdx.utils.GdxRuntimeException at O2DDialogTest.java:28```

I appended the log [here](http://dontpad.com/overlap2d/SerializationException)

**Comment by azakhary** [comment]
@htynkn may know more about this

**Comment by htynkn** [comment]
yeah, try this `./gradlew packTextures` first

**Comment by htynkn** [comment]
I'm not sure does every test works now... If still have some issue when running test please try `-x test` to skip test.

**Comment by felipebueno** [comment]
Hey, it worked! I had to skip the tests tough. I'll take a look at it tomorrow.

Thanks, @htynkn :)

**Comment by htynkn** [comment]
hmm... I think now it works. Can we close this issue?
