### ISSUE TITLE
Gradle task "packTextures" failing in Eclipse IDE

### ISSUE THREAD

**Issue by biobob** [UnderwaterApps/overlap2d#137]
Console output:
```
Gradle Tasks: packTextures
Working Directory: C:\Users\IBM_ADMIN\git\overlap2d
Gradle Distribution: Gradle wrapper from target build
Gradle User Home: Use default defined by Gradle
Java Home: Use default defined by Gradle
JVM Arguments: Use default defined by Gradle
Program Arguments: --stacktrace --info

Calling TexturePacker: [art/textures, assets/style/, uiskin]
:packTextures FAILED
:packTextures (Thread[Daemon worker Thread 21,5,main]) completed. Took 0.019 secs.
```
Failure:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\IBM_ADMIN\git\overlap2d\build.gradle' line: 73

* What went wrong:
Execution failed for task ':packTextures'.
> Error packing images.
```
Stacktrace:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packTextures'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	...
Caused by: java.lang.RuntimeException: Error packing images.
	at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:633)
	at com.badlogic.gdx.tools.texturepacker.TexturePacker.processIfModified(TexturePacker.java:669)
	at com.badlogic.gdx.tools.texturepacker.TexturePacker$processIfModified.call(Unknown Source)
	...
Caused by: java.lang.IllegalArgumentException: Input file does not exist: C:\Users\IBM_ADMIN\Eclipses\eclipse-mars\art\textures
	at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:117)
	at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:70)
	at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:631)
```
Directory `C:\Users\IBM_ADMIN\Eclipses\eclipse-mars\art\textures` obviously doesn't exist.
I assume that (at least in Eclipse IDE environment) when Java class is executed from the Gradle then current directory is changed to Eclipse root.

**Comment by azakhary** [comment]
Thanks!
