### ISSUE TITLE
Overlap2D crashes on startup on Ubuntu 15.04

### ISSUE THREAD

**Issue by CrackedP0t** [UnderwaterApps/overlap2d#168]
(I'm not sure if Linux is supposed to be supported or not)
Using Java 8 from the repos, I get these errors:
```
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:292)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:377)
	at com.uwsoft.editor.proxy.FontManager.getSystemFontFiles(FontManager.java:88)
	at com.uwsoft.editor.proxy.FontManager.preCacheSystemFontsMap(FontManager.java:95)
	at com.uwsoft.editor.proxy.FontManager.generateFontsMap(FontManager.java:132)
	at com.uwsoft.editor.proxy.FontManager.onRegister(FontManager.java:50)
	at com.puremvc.core.CoreModel.registerProxy(CoreModel.java:113)
	at com.puremvc.patterns.facade.SimpleFacade.registerProxy(SimpleFacade.java:235)
	at com.uwsoft.editor.controller.BootstrapProxyCommand.execute(BootstrapProxyCommand.java:41)
	at com.puremvc.patterns.command.MacroCommand.execute(MacroCommand.java:132)
	at com.puremvc.core.CoreController.executeCommand(CoreController.java:139)
	at com.puremvc.core.CoreController$$Lambda$21/875417129.onNotification(Unknown Source)
	at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
	at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
	at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
	at com.uwsoft.editor.Overlap2DFacade.startup(Overlap2DFacade.java:52)
	at com.uwsoft.editor.Overlap2D.create(Overlap2D.java:69)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
	at java.awt.Container.addImpl(Container.java:1119)
	at java.awt.Container.add(Container.java:415)
	at com.badlogic.gdx.backends.lwjgl.LwjglFrame.addCanvas(LwjglFrame.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglFrame$2.run(LwjglFrame.java:96)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
org.lwjgl.LWJGLException: X Error - disp: 0x7f0aa4457bd0 serial: 105 error: BadWindow (invalid Window parameter) request_code: 2 minor_code: 0
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxKeyboard.nSetDetectableKeyRepeat(Native Method)
	at org.lwjgl.opengl.LinuxKeyboard.setDetectableKeyRepeat(LinuxKeyboard.java:152)
	at org.lwjgl.opengl.LinuxKeyboard.destroy(LinuxKeyboard.java:163)
	at org.lwjgl.opengl.LinuxDisplay.destroyKeyboard(LinuxDisplay.java:1264)
	at org.lwjgl.input.Keyboard.destroy(Keyboard.java:357)
	at org.lwjgl.opengl.Display.destroyWindow(Display.java:349)
	at org.lwjgl.opengl.Display.access$400(Display.java:65)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:835)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:197)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:174)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:188)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4749)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4749)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4749)
	at javax.swing.JRootPane.addNotify(JRootPane.java:757)
	at java.awt.Container.addNotify(Container.java:2773)
	at java.awt.Window.addNotify(Window.java:770)
	at java.awt.Frame.addNotify(Frame.java:487)
	at java.awt.Window.show(Window.java:1031)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at com.badlogic.gdx.backends.lwjgl.LwjglFrame$2.run(LwjglFrame.java:97)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
	at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
	at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:92)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by azakhary** [comment]
create .fonts directory in your user home. And it will run.

**Comment by azakhary** [comment]
But let's not close the issue, I'll try to fix this crash bug tomorrow, so it will not crash regardless existance of that folder.

**Comment by CrackedP0t** [comment]
Great, it worked. Thanks!
