### ISSUE TITLE
box2d dependency is required?

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#169]
I'm not sure if the dependency was required in the old runtime
```
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.lang.ExceptionInInitializerError
	at com.uwsoft.editor.renderer.SceneLoader.initSceneLoader(SceneLoader.java:81)
	at com.uwsoft.editor.renderer.SceneLoader.<init>(SceneLoader.java:72)
	at de.dizayndesign.utils.overlap2d.O2DStageScreen.<init>(O2DStageScreen.kt:23)
	at de.lmgt.quiz.view.screens.TestScreen.<init>(TestScreen.kt:26)
	at de.lmgt.quiz.view.screens.MainMenuScreen$onAbout$1.invoke(MainMenuScreen.kt:88)
	at de.lmgt.quiz.view.screens.MainMenuScreen$onAbout$1.invoke(MainMenuScreen.kt:49)
	at de.lmgt.quiz.view.screens.MainMenuScreen$button$1.invoke(MainMenuScreen.kt:190)
	at de.lmgt.quiz.view.screens.MainMenuScreen$button$1.invoke(MainMenuScreen.kt:49)
	at de.lmgt.quiz.misc.MiscPackage$SoundedClick$becdf8c1$soundedClick$1.clicked(SoundedClick.kt:19)
	at de.lmgt.quiz.misc.SoundedClick.clicked(SoundedClick.kt:43)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx-box2d64.dll' for target: Windows 8.1, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:118)
	at com.badlogic.gdx.physics.box2d.World.<clinit>(World.java:187)
	... 17 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx-box2d64.dll
	at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:126)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:261)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:115)
	... 18 more
```

**Comment by kutoman** [comment]
or how to solve this?

**Comment by azakhary** [comment]
Does your project has box2d ?

Btw this will become optional tomorrow. But you need world if you plan to use either lights or physics.

**Comment by kutoman** [comment]
yes it shows gdx-box2d-1.6.2 as external library but I don't need box2d in my project

**Comment by kutoman** [comment]
I suppose it's still in progress? I still get the same exception

**Comment by azakhary** [comment]
yes it is. because I am not sure how to approach this, should some how group "all things physics" to make them happen only on physics enabled.

**Comment by kutoman** [comment]
I see, might be tough to handle
