### ISSUE TITLE
o2d-runtime box2d java.lang.NullPointerException 

### ISSUE THREAD

**Issue by PkayJava** [UnderwaterApps/overlap2d#177]
It happen when I remove a physics entity from the engine in the first time, before a render execution is called, body object is created only when first render execution

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.physics.box2d.World.destroyBody(World.java:320)
	at com.uwsoft.editor.renderer.SceneLoader$1.entityRemoved(SceneLoader.java:223)
	at com.badlogic.ashley.core.Engine.updateFamilyMembership(Engine.java:374)
	at com.badlogic.ashley.core.Engine.removeEntityInternal(Engine.java:395)
	at com.badlogic.ashley.core.Engine.removeEntity(Engine.java:148)
	at com.mygdx.game.Overlap2DEngine.create(Overlap2DEngine.java:65)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by azakhary** [comment]
oh right, had to add a null check there.

**Comment by azakhary** [comment]
Thanks, merged!
