### ISSUE TITLE
Drag "Text Button" cause app to crash

### ISSUE THREAD

**Issue by whitegfx** [UnderwaterApps/overlap2d#18]
After drag Text Button to scene, dialog appear and ask "there is no style...want to add", clicked Okay and app crash with this exception.

dev stack: osx 10.9.5, jdk 1.8, eclipse: 4.2.x, builded from sources

java.lang.NullPointerException
	at com.uwsoft.editor.data.JarUtils.copyResourcesToDirectory(JarUtils.java:83)
	at com.uwsoft.editor.data.manager.DataManager.copyDefaultStyleIntoProject(DataManager.java:807)
	at com.uwsoft.editor.gdx.sandbox.UserActionController$1.onConfirm(UserActionController.java:120)
	at com.uwsoft.editor.gdx.ui.dialogs.ConfirmDialog$1.touchUp(ConfirmDialog.java:45)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.jglfw.JglfwInput$1.touchUp(JglfwInput.java:92)
	at com.badlogic.gdx.InputProcessorQueue.drain(InputProcessorQueue.java:80)
	at com.badlogic.gdx.backends.jglfw.JglfwInput.update(JglfwInput.java:138)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.frame(JglfwApplication.java:212)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.start(JglfwApplication.java:197)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.initialize(JglfwApplication.java:177)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication$1.run(JglfwApplication.java:87)
	at java.lang.Thread.run(Thread.java:745)
Source 'assets/ui' does not exist
java.io.FileNotFoundException: Source 'assets/ui' does not exist
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:776)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:744)
	at com.uwsoft.editor.data.manager.DataManager.copyDefaultStyleIntoProject(DataManager.java:817)
	at com.uwsoft.editor.gdx.sandbox.UserActionController$1.onConfirm(UserActionController.java:120)
	at com.uwsoft.editor.gdx.ui.dialogs.ConfirmDialog$1.touchUp(ConfirmDialog.java:45)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.jglfw.JglfwInput$1.touchUp(JglfwInput.java:92)
	at com.badlogic.gdx.InputProcessorQueue.drain(InputProcessorQueue.java:80)
	at com.badlogic.gdx.backends.jglfw.JglfwInput.update(JglfwInput.java:138)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.frame(JglfwApplication.java:212)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.start(JglfwApplication.java:197)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.initialize(JglfwApplication.java:177)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication$1.run(JglfwApplication.java:87)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at com.badlogic.gdx.scenes.scene2d.ui.TextButton.<init>(TextButton.java:33)
	at com.uwsoft.editor.renderer.actor.TextButtonItem.<init>(TextButtonItem.java:32)
	at com.uwsoft.editor.renderer.actor.TextButtonItem.<init>(TextButtonItem.java:27)
	at com.uwsoft.editor.gdx.sandbox.ItemFactory.createComponent(ItemFactory.java:203)
	at com.uwsoft.editor.gdx.sandbox.UserActionController$1.onConfirm(UserActionController.java:121)
	at com.uwsoft.editor.gdx.ui.dialogs.ConfirmDialog$1.touchUp(ConfirmDialog.java:45)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.jglfw.JglfwInput$1.touchUp(JglfwInput.java:92)
	at com.badlogic.gdx.InputProcessorQueue.drain(InputProcessorQueue.java:80)
	at com.badlogic.gdx.backends.jglfw.JglfwInput.update(JglfwInput.java:138)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.frame(JglfwApplication.java:212)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.start(JglfwApplication.java:197)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.initialize(JglfwApplication.java:177)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication$1.run(JglfwApplication.java:87)
	at java.lang.Thread.run(Thread.java:745)

**Comment by whitegfx** [comment]
Temp workaround is to copy Overlap2D_007/examples/OverlapDemo/assets/orig/styles to new project.
Put these styles to newly created project?

**Comment by azakhary** [comment]
Fixed in #75
