### ISSUE TITLE
error when entering Composite item

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#181]
the editor crashes with this stack trace when I double click on a certain composite item:

java.lang.IndexOutOfBoundsException: index can't be >= size: 9 >= 9
        at com.badlogic.gdx.utils.Array.get(Array.java:127)
        at com.uwsoft.editor.view.ui.box.UILayerBox.setCurrentSelectedLayer(UILayerBox.java:148)
        at com.uwsoft.editor.view.ui.box.UILayerBoxMediator.handleNotification(UILayerBoxMediator.java:100)
        at com.puremvc.core.CoreView$$Lambda$21/733663039.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:337)
        at com.uwsoft.editor.controller.commands.CompositeCameraChangeCommand.doAction(CompositeCameraChangeCommand.java
:63)
        at com.uwsoft.editor.controller.commands.RevertableCommand.callDoAction(RevertableCommand.java:49)
        at com.uwsoft.editor.controller.commands.RevertableCommand.execute(RevertableCommand.java:40)
        at com.puremvc.core.CoreController.executeCommand(CoreController.java:139)
        at com.puremvc.core.CoreController$$Lambda$19/1172317879.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:337)
        at com.uwsoft.editor.view.stage.tools.SelectionTool.itemMouseDoubleClick(SelectionTool.java:302)
        at com.uwsoft.editor.view.stage.SandboxMediator$SandboxItemEventListener.touchUp(SandboxMediator.java:227)
        at com.uwsoft.editor.view.stage.input.SandboxInputAdapter.touchUp(SandboxInputAdapter.java:136)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.spatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
        at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
        at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
        at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
        at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
        at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
        at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
        at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:92)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kutoman** [comment]
I suppose it's somehow linked to #158, as I struggled with the layers and copy pasting items on those layers

**Comment by azakhary** [comment]
Layers are so messed up :((((((((

**Comment by kutoman** [comment]
true that :D, can I help you concerning that issue?

**Comment by azakhary** [comment]
You already helped so much I cannot even say thank you enough, biggest contributor so far :-P ;) As for this issue, it's kinda so messed up, I have no idea where to start myself, rather then just to look at it, and think think think.

**Comment by kutoman** [comment]
You're welcome, I also have to be thankful for this great tool. It's just the missing part for libgdx, and makes its game development so much easier. I like to be helpful when I'm able to. So just let me know if I can contribute in this context, since this issue has to be fixed as so much stuff relies on a robust layer management. I'm aware that it might take a lot time to fix that up.

**Comment by azakhary** [comment]
I have this current approach of... let's try to fix layer bugs one by one, and if it persists for 5 more bugs, we rewrite the thing..... sounds legit? :D

**Comment by kutoman** [comment]
yeah sure

**Comment by azakhary** [comment]
Hey, is there any way we can reproduce this? if you remember the steps?

**Comment by kutoman** [comment]
unfortunately I do not have that composite item anymore and I don't remember the exact steps. But as I recently experimented (and it seems to be the same error), I noticed this:
to reproduce:
-just create a new image item
-convert it into a composite
-enter that composite
-lock the default layer
-leave the composite
-> try to reenter the composite

**Comment by azakhary** [comment]
That one - fixed, pushed.
Now if we only know this solves the bigger picture :D

**Comment by kutoman** [comment]
alright :+1: :)

**Comment by azakhary** [comment]
so. let me close this one. And if it happens again, let's reopen.
