### ISSUE TITLE
Crash after renaming an item and clicking on the layers box in a composite item

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#188]
Unfortunately I don't know how to reproduce but I get the following:
```
java.lang.NullPointerException
        at com.uwsoft.editor.view.ui.FollowersUIMediator.setNewSelectionConfiguration(FollowersUIMediator.java:150)
        at com.uwsoft.editor.view.ui.FollowersUIMediator.handleNotification(FollowersUIMediator.java:109)
        at com.puremvc.core.CoreView$$Lambda$21/842581056.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:337)
        at com.uwsoft.editor.view.stage.ItemSelector.setSelection(ItemSelector.java:218)
        at com.uwsoft.editor.view.stage.ItemSelector.addSelections(ItemSelector.java:227)
        at com.uwsoft.editor.controller.commands.AddSelectionCommand.doAction(AddSelectionCommand.java:46)
        at com.uwsoft.editor.controller.commands.RevertableCommand.callDoAction(RevertableCommand.java:49)
        at com.uwsoft.editor.controller.commands.RevertableCommand.execute(RevertableCommand.java:40)
        at com.puremvc.core.CoreController.executeCommand(CoreController.java:139)
        at com.puremvc.core.CoreController$$Lambda$19/2107570859.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:337)
        at com.uwsoft.editor.view.ui.box.UILayerBoxMediator.selectEntitiesByLayerName(UILayerBoxMediator.java:275)
        at com.uwsoft.editor.view.ui.box.UILayerBoxMediator.handleNotification(UILayerBoxMediator.java:120)
        at com.puremvc.core.CoreView$$Lambda$21/842581056.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:337)
        at com.uwsoft.editor.view.ui.box.UILayerBox$3.clicked(UILayerBox.java:188)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThmpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
        at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
        at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
        at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
        at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
        at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
        at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
        at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:92)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by saltares** [comment]
I'm finding it hard to reproduce this one.
