### ISSUE TITLE
crashing after composite conversion

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#209]
after a composite conversion and clicking on canvas, the editor crashes. The weird thing is, that I cannot reproduce it in other projects or on other scenes. It only happens on that certain scene, I'm working on

```
java.lang.NullPointerException
	at com.uwsoft.editor.view.stage.tools.SelectionTool.isEntityVisible(SelectionTool.java:357)
	at com.uwsoft.editor.view.stage.tools.SelectionTool.selectionComplete(SelectionTool.java:339)
	at com.uwsoft.editor.view.stage.tools.SelectionTool.stageMouseUp(SelectionTool.java:109)
	at com.uwsoft.editor.view.stage.SandboxMediator$SandboxStageEventListener.touchUp(SandboxMediator.java:387)
	at com.uwsoft.editor.view.stage.input.SandboxInputAdapter.touchUp(SandboxInputAdapter.java:127)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
	at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
	at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:92)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kutoman** [comment]
ah I found the reason. The scene I was working on does not have a "Default" layer. The newly converted composite item by default is assigned to the "Default" layer, which causes that NPE if the layer does not exist.

**Comment by kutoman** [comment]
I think the new composite item should be assigned to the lowermost layer, where a child item is on, instead?

**Comment by azakhary** [comment]
hmm, that has to be fixed, composite should be assigned to "any" layer or currently selected. gaving default layer is not mandatory

**Comment by kutoman** [comment]
yes the currently selected one is the best fit I think

**Comment by kutoman** [comment]
I fıx that
