### ISSUE TITLE
Application crashes when clicking the root image after changing resolution

### ISSUE THREAD

**Issue by billy1380** [UnderwaterApps/overlap2d#211]
I am running version 0.1.1 on ubuntu. The application crashes when the root image

![selection_009](https://cloud.githubusercontent.com/assets/1329727/9419343/bdf5f8c2-4852-11e5-9709-e6d7d1c7e3a4.png)

 is clicked but only after the resolution is changed
 
![selection_010](https://cloud.githubusercontent.com/assets/1329727/9419346/c2bc0f9a-4852-11e5-8384-cfd7ae31d305.png)

I am testing using the overlap2d demo project.

The exception is:

``` java
java.util.NoSuchElementException: 0
	at com.badlogic.gdx.utils.Array$ArrayIterator.next(Array.java:543)
	at com.uwsoft.editor.view.stage.SandboxMediator.initItemListeners(SandboxMediator.java:154)
	at com.uwsoft.editor.view.stage.SandboxMediator.handleNotification(SandboxMediator.java:129)
	at com.puremvc.core.CoreView$$Lambda$22/1309725948.onNotification(Unknown Source)
	at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
	at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
	at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
	at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
	at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:337)
	at com.uwsoft.editor.controller.commands.CompositeCameraChangeCommand.doAction(CompositeCameraChangeCommand.java:63)
	at com.uwsoft.editor.controller.commands.RevertableCommand.callDoAction(RevertableCommand.java:49)
	at com.uwsoft.editor.controller.commands.RevertableCommand.execute(RevertableCommand.java:40)
	at com.puremvc.core.CoreController.executeCommand(CoreController.java:139)
	at com.puremvc.core.CoreController$$Lambda$21/896436574.onNotification(Unknown Source)
	at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
	at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
	at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
	at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
	at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:337)
	at com.uwsoft.editor.view.ui.box.UICompositeHierarchyMediator.handleNotification(UICompositeHierarchyMediator.java:53)
	at com.puremvc.core.CoreView$$Lambda$22/1309725948.onNotification(Unknown Source)
	at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
	at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
	at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
	at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
	at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:337)
	at com.uwsoft.editor.view.ui.box.UICompositeHierarchy$1.clicked(UICompositeHierarchy.java:46)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
	at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
	at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:92)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by saltares** [comment]
It seems that `CompositeCameraChangeCommand` gets executed when the user clicks on the root image on the editor.

In the [`doAction()`](https://github.com/UnderwaterApps/overlap2d/blob/master/overlap2d/src/com/uwsoft/editor/controller/commands/CompositeCameraChangeCommand.java#L52) the `ViewportComponent` passes from one entity to another. Strangely, the new entity might not be in the engine yet! This means that when [`initItemListeners()`](https://github.com/UnderwaterApps/overlap2d/blob/master/overlap2d/src/com/uwsoft/editor/view/stage/SandboxMediator.java#L154) gets called in `SandboxMediator`, there will be no entities with the `ViewportComponent`, therefore it crashes.

Two questions for @azakhary:
* What does clicking on the root image mean? What is it meant to do?
* Why isn't the new entity with the `ViewportComponent` in the engine?

**Comment by azakhary** [comment]
that's weird, I don't imagine a scenario where entity with viewport is not inside engine, at least on first sight.

Answering the questions:
1) clicking on root is supposed to set vewport component to well, root entity, the one that is above all in hierarchy. 
2) That is a good question, does resolution change happen while being inside a composite? Need more info on reproducing.
