### ISSUE TITLE
Crash when trying to use Text tool (Linuxmint, ArchLinux)

### ISSUE THREAD

**Issue by yichen0831** [UnderwaterApps/overlap2d#277]
With overlap2d-0.1.1, after choosing the Text tool on the left panel and clicking on the scene screen, the program crashes right away. (on both Linuxmint and ArchLinux)

Here's the message:

java.lang.NullPointerException
	at com.uwsoft.editor.view.stage.tools.SelectionTool.isEntityVisible(SelectionTool.java:357)
	at com.uwsoft.editor.view.stage.tools.SelectionTool.itemMouseDown(SelectionTool.java:143)
	at com.uwsoft.editor.view.stage.SandboxMediator$SandboxItemEventListener.touchDown(SandboxMediator.java:210)
	at com.uwsoft.editor.view.stage.input.SandboxInputAdapter.touchDown(SandboxInputAdapter.java:105)
	at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:303)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
	at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
	at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:92)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
yichen@V3-571G:~/Downloads/overlap2d$ java -jar overlap2D-0.1.1.jar 
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.badlogic.gdx.files.FileHandle.<init>(FileHandle.java:62)
	at com.uwsoft.editor.proxy.FontManager.getTTFByName(FontManager.java:160)
	at com.uwsoft.editor.proxy.ResourceManager.prepareEmbeddingFont(ResourceManager.java:364)
	at com.uwsoft.editor.factory.ItemFactory.createLabel(ItemFactory.java:211)
	at com.uwsoft.editor.view.stage.tools.TextTool.putItem(TextTool.java:63)
	at com.uwsoft.editor.view.stage.tools.ItemDropTool.stageMouseDown(ItemDropTool.java:17)
	at com.uwsoft.editor.view.stage.SandboxMediator$SandboxStageEventListener.touchDown(SandboxMediator.java:377)
	at com.uwsoft.editor.view.stage.input.SandboxInputAdapter.touchDown(SandboxInputAdapter.java:91)
	at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:303)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
	at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
	at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:92)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Keftaa** [comment]
I'm having the exact same problem on Debian Sid, but with a different error message.
```
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.badlogic.gdx.files.FileHandle.<init>(FileHandle.java:62)
	at com.uwsoft.editor.proxy.FontManager.getTTFByName(FontManager.java:160)
	at com.uwsoft.editor.proxy.ResourceManager.prepareEmbeddingFont(ResourceManager.java:364)
	at com.uwsoft.editor.factory.ItemFactory.createLabel(ItemFactory.java:223)
	at com.uwsoft.editor.view.stage.tools.TextTool.putItem(TextTool.java:63)
	at com.uwsoft.editor.view.stage.tools.ItemDropTool.stageMouseDown(ItemDropTool.java:17)
	at com.uwsoft.editor.view.stage.SandboxMediator$SandboxStageEventListener.touchDown(SandboxMediator.java:377)
	at com.uwsoft.editor.view.stage.input.SandboxInputAdapter.touchDown(SandboxInputAdapter.java:91)
	at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:303)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
	at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
	at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:68)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Can't wait to start tinkering with Overlap2D !

**Comment by StQuote** [comment]
For me is reproduced too. Linux Mint 17

```
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.badlogic.gdx.files.FileHandle.<init>(FileHandle.java:62)
	at com.uwsoft.editor.proxy.FontManager.getTTFByName(FontManager.java:160)
	at com.uwsoft.editor.proxy.ResourceManager.prepareEmbeddingFont(ResourceManager.java:364)
	at com.uwsoft.editor.factory.ItemFactory.createLabel(ItemFactory.java:223)
	at com.uwsoft.editor.view.stage.tools.TextTool.putItem(TextTool.java:63)
	at com.uwsoft.editor.view.stage.tools.ItemDropTool.stageMouseDown(ItemDropTool.java:17)
	at com.uwsoft.editor.view.stage.SandboxMediator$SandboxStageEventListener.touchDown(SandboxMediator.java:386)
	at com.uwsoft.editor.view.stage.input.SandboxInputAdapter.touchDown(SandboxInputAdapter.java:91)
	at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:303)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
	at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:65)
	at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:68)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by azakhary** [comment]
For linux Overlap2D is looking for your system fonts in user home .fonts directory. If there is no fonts, no label can be placed and it will crash. A quick fix is to just add some ttf fonts there.

**Comment by StQuote** [comment]
I checked the source code and decided that main problem is that `getSystemFontsPaths` method in FontManager class return empty Array.

So editor 'thinks' that system doesn't have installed fonts and this case not handled in `createLabel` method of ItemFactory class (223 line).

**Comment by azakhary** [comment]
we can definitely add a check in createLabel to prevent the crash, but that will not fix the main problem of not finding a font. Is there a better path to look in then the current one? for example, where are the fonts on your linux system?

**Comment by StQuote** [comment]
Yeah, if place fonts in ~/.fonts directory (which not system default) it's should be work. But it's seems like a dirty hack :)

I think will be better to scan /usr/share/fonts/truetype for default fonts. Based on this [StackOverflow](http://superuser.com/questions/137826/location-of-truetype-fonts) answer is should be common path for all major distros, like Ubuntu, Mint, Fedora etc

**Comment by azakhary** [comment]
oh. Got it. then why not both? That seems like a valid fix to scan several folders for linux.

**Comment by azakhary** [comment]
So, yeah let me know if you feel like doing a PR, if not, I can fix it later in near 2 days.

**Comment by StQuote** [comment]
Sure, need to be scanned both this paths. I can try to fix this. 

Structure a little bit complex than in Windows (each font family grouped in directories) and I'm not sure how many 'children' groups can be. So maybe is should be scanned recursively?

For me directory structure in /usr/share/fonts/truetype seems like this:
```
.
├── abyssinica
│   └── AbyssinicaSIL-R.ttf
├── dejavu
│   ├── DejaVuSans-BoldOblique.ttf
│   └── DejaVuSerif.ttf
├── droid
│   ├── DroidNaskh-Bold.ttf
│   └── DroidSerif-Regular.ttf
├── kacst-one
│   ├── KacstOne-Bold.ttf
│   └── KacstOne.ttf
├── lao
│   └── Phetsarath_OT.ttf
```
*There is more folders with many ttf fonts.*

**Comment by azakhary** [comment]
yeah probably recursively is the way to go, there in Font Manager we have a special if block for linux only where it checks only one folder, and that can be changed. But also I guess some checks to make sure we don't crash if user does not have the folder we are trying to scan.

**Comment by StQuote** [comment]
Okey, I'll try to do this. 

Default paths for scan its will be '/usr/share/truetype' and '~/.fonts'. But if both of this paths is not exists, whats should happen?

**Comment by azakhary** [comment]
if both not there I guess user maybe has no fonts, in that case, createLabel should just see that there is no fonts and not crash. (I'll add some error dialog later)

**Comment by StQuote** [comment]
Ok, I'll create pullrequest when i'm done.

**Comment by azakhary** [comment]
Thanks a lot! this was very much needed for all Linux users of o2d out there. Much appreciated!

**Comment by StQuote** [comment]
You are welcome.

P.S. Thanks you for great tool! I think o2d has a great potential.

**Comment by rodri042** [comment]
I'm using Fedora 23 and I'm getting the same error here. I don't have a `/usr/share/fonts/truetype` dir.

I have created a symlink in `/usr/share/fonts/truetype` to `/usr/share/fonts`, and everything worked but it's a dirty hack.
It would be great if O2D searches recursivelly directly in `usr/share/fonts` because it's more generic and more distros will be targeted :smile:
