### ISSUE TITLE
Crashes out when loading sprite animation frames (ported issue from Forums)

### ISSUE THREAD

**Issue by robcowell** [UnderwaterApps/overlap2d#307]
Trying to load a sprite animation by multi-selecting multi frames (7 x PNG) and it crashes out the editor. If I reload the editor, it crashes repeatedly until I delete /assets/orig/spriteanimations folder and /assets/orig/spriteanimations.png

Debug log :
```
/Users/robcowell/Desktop/FishFrames/2 (alias of /Users/robcowell/Desktop/FishFrames/0)
/Users/robcowell/Desktop/FishFrames/4 (alias of /Users/robcowell/Desktop/FishFrames/3)
/Users/robcowell/Desktop/FishFrames/7 (alias of /Users/robcowell/Desktop/FishFrames/5)
Packing..
Writing 256×256: /Users/robcowell/o2dtest/o2dtest/assets/orig/sprite-animations.png
Creating directory: /Users/robcowell/o2dtest/o2dtest/assets/orig/sprite-animations/tmp
javax.imageio.IIOException: Can’t read input file!
at javax.imageio.ImageIO.read(ImageIO.java:1301)
at com.badlogic.gdx.tools.texturepacker.TextureUnpacker.splitAtlas(TextureUnpacker.java:85)
at com.uwsoft.editor.proxy.ResolutionManager.unpackAtlasIntoTmpFolder(ResolutionManager.java:250)
at com.uwsoft.editor.proxy.ResolutionManager.resizeSpriteAnimationForAllResolutions(ResolutionManager.java:286)
at com.uwsoft.editor.proxy.ProjectManager.lambda$importSpriteAnimationsIntoProject$10(ProjectManager.java:454)
at com.uwsoft.editor.proxy.ProjectManager$$Lambda$32/1545848934.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

PNG files attached - GitHub doesn't support ZIP attachments

![0](https://cloud.githubusercontent.com/assets/2143167/11102599/6ca027a6-88b5-11e5-9244-c14066860cf5.png)
![1](https://cloud.githubusercontent.com/assets/2143167/11102598/6c9ff308-88b5-11e5-9772-fc6c874a84b8.png)
![2](https://cloud.githubusercontent.com/assets/2143167/11102597/6c9fb780-88b5-11e5-8d06-03f2f9e416de.png)
![3](https://cloud.githubusercontent.com/assets/2143167/11102600/6ca26ff2-88b5-11e5-9428-c422efacd916.png)
![4](https://cloud.githubusercontent.com/assets/2143167/11102596/6c9f3198-88b5-11e5-91b2-1b17d4b476b7.png)
![5](https://cloud.githubusercontent.com/assets/2143167/11102601/6ca27f88-88b5-11e5-93a0-1d09c97027d1.png)
![6](https://cloud.githubusercontent.com/assets/2143167/11102603/6cb7f76e-88b5-11e5-8daa-6b03fceed274.png)
![7](https://cloud.githubusercontent.com/assets/2143167/11102602/6cb5e758-88b5-11e5-8680-c86ad1bcbce1.png)

**Comment by azakhary** [comment]
the images you are importing, have to have sequential numbers with no number missing, as in:  anim001, anim002, anim003 e.g. So that will solve it for you. But that's also a bug, because overlap2d should have considered this a "no animation" and import just as regular images, because this does not follow animation name convention for import. So has to be fixed as well.

**Comment by robcowell** [comment]
GitHub renamed the files - here's a screnshot of the original filenames... should this have worked?  Could it be that it needs to start from 1, not 0 ?
![animation](https://cloud.githubusercontent.com/assets/2143167/11102813/a8f4387c-88b6-11e5-897b-c8c7566b206c.png)

**Comment by azakhary** [comment]
oh. this should have worked. can you try having some letter or something before the numbers, instead of just numbers, just to test? I think it might be it. But definitely a bug on our side.

**Comment by robcowell** [comment]
Yes, prefixing them with text has fixed it, thanks.

**Comment by azakhary** [comment]
I'll take a look at this.

**Comment by robcowell** [comment]
Thanks for responding so quickly, appreciated

**Comment by azakhary** [comment]
The issue is, when you provide something like fish001, fish002 it imports it and names animation "fish". No here it had no idea on how to name the animation. I guess the correct behavior would be to generate random string as anim name. But then it will not be searchable in asset panel. So in any case it's recommended to have a name in file. Another thing we can do is show a dialog and ask for a name and rename that files for you.

**Comment by robcowell** [comment]
Option 2 sounds the sensible choice to me
