### ISSUE TITLE
overlap2d not starting since last pull

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#326]
getting the following error (btw. visuiVersion could be set to '0.9.4')

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: com.uwsoft.editor.view.ui.dialog.NewProjectDialog.createValidableTextField(Ljava/lang/String;Lcom/kotcrab/vis/ui/InputValidator;)Lcom/kotcrab/vis/ui/widget/VisValidatableTe
xtField;
        at com.uwsoft.editor.view.ui.dialog.NewProjectDialog.<init>(NewProjectDialog.java:61)
        at com.uwsoft.editor.view.ui.dialog.NewProjectDialogMediator.<init>(NewProjectDialogMediator.java:37)
        at com.uwsoft.editor.controller.BootstrapViewCommand.execute(BootstrapViewCommand.java:60)
        at com.puremvc.patterns.command.MacroCommand.execute(MacroCommand.java:132)
        at com.puremvc.core.CoreController.executeCommand(CoreController.java:139)
        at com.puremvc.core.CoreController$$Lambda$19/2120607931.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.uwsoft.editor.Overlap2DFacade.startup(Overlap2DFacade.java:52)
        at com.uwsoft.editor.Overlap2D.create(Overlap2D.java:45)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
        at java.awt.Container.addImpl(Container.java:1119)
        at java.awt.Container.add(Container.java:415)
        at com.badlogic.gdx.backends.lwjgl.LwjglFrame.addCanvas(LwjglFrame.java:135)
        at com.badlogic.gdx.backends.lwjgl.LwjglFrame$2.run(LwjglFrame.java:96)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kutoman** [comment]
by changing the version to at least 0.9.3 the error changed

com.badlogic.gdx.utils.SerializationException: Error reading file: style/uiskin.json
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:97)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:74)
        at com.kotcrab.vis.ui.VisUI.load(VisUI.java:98)
        at com.uwsoft.editor.Overlap2D.create(Overlap2D.java:42)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
        at java.awt.Container.addImpl(Container.java:1119)
        at java.awt.Container.add(Container.java:415)
        at com.badlogic.gdx.backends.lwjgl.LwjglFrame.addCanvas(LwjglFrame.java:135)
        at com.badlogic.gdx.backends.lwjgl.LwjglFrame$2.run(LwjglFrame.java:96)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: style/uiskin.json
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:683)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:95)
        ... 23 more
Caused by: com.badlogic.gdx.utils.SerializationException: Field not found: white (com.kotcrab.vis.ui.widget.color.ColorP
ickerStyle)
        at com.badlogic.gdx.utils.Json.readFields(Json.java:776)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:902)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:404)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:834)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.readNamedObjects(Skin.java:425)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:414)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:410)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:867)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:404)
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:681)
        ... 24 more
com.badlogic.gdx.utils.SerializationException: Error reading file: style/uiskin.json
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:97)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:74)
        at com.kotcrab.vis.ui.VisUI.load(VisUI.java:98)
        at com.uwsoft.editor.Overlap2D.create(Overlap2D.java:42)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at javax.swing.JRootPane.addNotify(JRootPane.java:757)
        at java.awt.Container.addNotify(Container.java:2773)
        at java.awt.Window.addNotify(Window.java:770)
        at java.awt.Frame.addNotify(Frame.java:487)
        at java.awt.Window.show(Window.java:1031)
        at java.awt.Component.show(Component.java:1654)
        at java.awt.Component.setVisible(Component.java:1606)
        at java.awt.Window.setVisible(Window.java:1014)
        at com.badlogic.gdx.backends.lwjgl.LwjglFrame$2.run(LwjglFrame.java:97)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: style/uiskin.json
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:683)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:95)
        ... 34 more
Caused by: com.badlogic.gdx.utils.SerializationException: Field not found: white (com.kotcrab.vis.ui.widget.color.ColorP
ickerStyle)
        at com.badlogic.gdx.utils.Json.readFields(Json.java:776)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:902)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:404)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:834)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.readNamedObjects(Skin.java:425)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:414)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:410)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:867)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:404)
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:681)
        ... 35 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.uwsoft.editor.Overlap2D.sendNotification(Overlap2D.java:83)
        at com.uwsoft.editor.Overlap2D.pause(Overlap2D.java:51)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:308)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

BUILD SUCCESSFUL

**Comment by azakhary** [comment]
Is it eclipse?

**Comment by kutoman** [comment]
I'm used to run overlap2d from the command line

**Comment by azakhary** [comment]
That's weird. it was working for me fine. what we did was to just upgrade latest VisUI, but I am not sure why it is not starting for you in particular. Maybe some gradle cache thingie?

**Comment by kutoman** [comment]
oh :( I noticed that long time ago (due to uiskin modifications I didn't want to commit), I put these lines 
`assets/style/uiskin.png
assets/style/uiskin.atlas`
in .gitignore

**Comment by azakhary** [comment]
Does that fix the problem?

**Comment by kutoman** [comment]
I'm still trying to figure out how to remove these files from gitignore :S..

**Comment by kutoman** [comment]
I'm wondering about one thing. In the assets folder there are two uiskin atlasses (one in the folder itself and one in the subfolder "overlap2d"). Why is that?

**Comment by azakhary** [comment]
I am curious about that as well, at some point it got there. And I am not sure why, but I can't just delete it, until I investigate.

**Comment by kutoman** [comment]
ok

**Comment by kutoman** [comment]
well the error says:
``Caused by: com.badlogic.gdx.utils.SerializationException: Field not found: white (com.kotcrab.vis.ui.widget.color.ColorP
ickerStyle)``
but as I checked the atlas file, the field does exist..

``
  "com.kotcrab.vis.ui.widget.color.ColorPickerStyle": {
    "default": {
      "white": "white",
      "alphaBar10px": "alpha-bar-10px",
      "alphaBar25px": "alpha-bar-25px",
      "barSelector": "color-picker-bar-selector",
      "cross": "color-picker-cross",
      "verticalSelector": "color-picker-selector-vertical",
      "horizontalSelector": "color-picker-selector-horizontal"
    }
  },
``

**Comment by azakhary** [comment]
Maybe you have several files (with same name in other folder) and in your case it is reading from the other one. check if you have that file somewhere else, and update it with the last one.

**Comment by kutoman** [comment]
ok I proceeded as follows. Rebuilt the project with gradle and then copied the content of uiskin.json to uiskin.atlas (uiskin.json seems to be deprecated), now I'm getting a newer error:
``
com.badlogic.gdx.utils.GdxRuntimeException: Error reading pack file: style/uiskin.atlas
        at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:187)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:70)
        at com.kotcrab.vis.ui.VisUI.load(VisUI.java:98)
        at com.uwsoft.editor.Overlap2D.create(Overlap2D.java:42)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
        at java.awt.Container.addImpl(Container.java:1119)
        at java.awt.Container.add(Container.java:415)
        at com.badlogic.gdx.backends.lwjgl.LwjglFrame.addCanvas(LwjglFrame.java:135)
        at com.badlogic.gdx.backends.lwjgl.LwjglFrame$2.run(LwjglFrame.java:96)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: No enum constant com.badlogic.gdx.graphics.Pixmap.Format.{
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.badlogic.gdx.graphics.Pixmap$Format.valueOf(Pixmap.java:49)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:120)
        ... 26 more
com.badlogic.gdx.utils.GdxRuntimeException: Error reading pack file: style/uiskin.atlas
        at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:187)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:70)
        at com.kotcrab.vis.ui.VisUI.load(VisUI.java:98)
        at com.uwsoft.editor.Overlap2D.create(Overlap2D.java:42)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at javax.swing.JRootPane.addNotify(JRootPane.java:757)
        at java.awt.Container.addNotify(Container.java:2773)
        at java.awt.Window.addNotify(Window.java:770)
        at java.awt.Frame.addNotify(Frame.java:487)
        at java.awt.Window.show(Window.java:1031)
        at java.awt.Component.show(Component.java:1654)
        at java.awt.Component.setVisible(Component.java:1606)
        at java.awt.Window.setVisible(Window.java:1014)
        at com.badlogic.gdx.backends.lwjgl.LwjglFrame$2.run(LwjglFrame.java:97)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: No enum constant com.badlogic.gdx.graphics.Pixmap.Format.{
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.badlogic.gdx.graphics.Pixmap$Format.valueOf(Pixmap.java:49)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:120)
        ... 37 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.uwsoft.editor.Overlap2D.sendNotification(Overlap2D.java:83)
        at com.uwsoft.editor.Overlap2D.pause(Overlap2D.java:51)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:308)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

BUILD SUCCESSFUL

Total time: 33.254 secs
``

**Comment by kutoman** [comment]
Im kinda confused at the moment what is the purpose of having uiskin.json and uiskin.atlas? I actually thought one of them is legacy

**Comment by azakhary** [comment]
JSON is the skins and atlas is the texture region list. no?

**Comment by kutoman** [comment]
makes sense since the content is based on that, but when overlap2d is loading, it is looking for the field `white` (com.kotcrab.vis.ui.widget.color.ColorPickerStyle) in uiskin.atlas but not in uiskin.json

**Comment by kutoman** [comment]
oh wait, I'm mistaken, it's related to uiskin.json... hmm

**Comment by kutoman** [comment]
the weird thing is, there is only one uiskin.json file in the whole project, and it does contain the respective style and field. But the error says: Error reading file: style/uiskin.json .... Field not found: white (com.kotcrab.vis.ui.widget.color.ColorPickerStyle)

**Comment by kutoman** [comment]
this seems to be a caching issue of gradle as you said (I've misread the error), the ColorPickerStyle class seems to be an old one.. I'll try to fix that

**Comment by kutoman** [comment]
fixed
