### ISSUE TITLE
Application crash on "File/Open Project" If the last opened path does not exist

### ISSUE THREAD

**Issue by ihitang** [UnderwaterApps/overlap2d#327]
I've fix it via changing the lastOpenedSystemPath in config.pit, but it is not the case

**Comment by azakhary** [comment]
can you post the stacktrace? This happened to me before. Would be easy to find if I have it.

**Comment by ihitang** [comment]
Creating new project:

D:\overlap2d>java -jar overlap2D-0.1.2.jar
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String)
)
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String)
)
java.io.FileNotFoundException: Source 'D:\overlap2d\my_folder\main\assets\shaders' does not exist
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:776)
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:744)
        at com.uwsoft.editor.proxy.ProjectManager.exportShaders(ProjectManager.java:861)
        at com.uwsoft.editor.proxy.ProjectManager.exportProject(ProjectManager.java:826)
        at com.uwsoft.editor.controller.commands.ExportProjectCommand.execute(ExportProjectCommand.java:31)
        at com.puremvc.core.CoreController.executeCommand(CoreController.java:139)
        at com.puremvc.core.CoreController$$Lambda$18/2018809316.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:350)
        at com.uwsoft.editor.view.menu.Overlap2DMenuBarMediator.handleFileMenuNotification(Overlap2DMenuBarMediator.java
:165)
        at com.uwsoft.editor.view.menu.Overlap2DMenuBarMediator.handleNotification(Overlap2DMenuBarMediator.java:101)
        at com.puremvc.core.CoreView$$Lambda$20/139288691.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.uwsoft.editor.event.MenuItemListener.changed(MenuItemListener.java:44)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:316)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
        at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
        at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
        at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.dispose(OpenALAudio.java:285)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$5.run(LwjglCanvas.java:411)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.executeRunnables(LwjglCanvas.java:261)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:227)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

2) remove/rename my folder
3) Trying to open menu item: File / Open Project
D:\overlap2d>java -jar overlap2D-0.1.2.jar
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String)
)
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String)
)
java.io.FileNotFoundException: Source 'D:\overlap2d\my_folder\main\assets\shaders' does not exist
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:776)
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:744)
        at com.uwsoft.editor.proxy.ProjectManager.exportShaders(ProjectManager.java:861)
        at com.uwsoft.editor.proxy.ProjectManager.exportProject(ProjectManager.java:826)
        at com.uwsoft.editor.controller.commands.ExportProjectCommand.execute(ExportProjectCommand.java:31)
        at com.puremvc.core.CoreController.executeCommand(CoreController.java:139)
        at com.puremvc.core.CoreController$$Lambda$18/2018809316.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:350)
        at com.uwsoft.editor.view.menu.Overlap2DMenuBarMediator.handleFileMenuNotification(Overlap2DMenuBarMediator.java
:165)
        at com.uwsoft.editor.view.menu.Overlap2DMenuBarMediator.handleNotification(Overlap2DMenuBarMediator.java:101)
        at com.puremvc.core.CoreView$$Lambda$20/139288691.onNotification(Unknown Source)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.uwsoft.editor.event.MenuItemListener.changed(MenuItemListener.java:44)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:316)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
        at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
        at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
        at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.dispose(OpenALAudio.java:285)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$5.run(LwjglCanvas.java:411)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.executeRunnables(LwjglCanvas.java:261)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:227)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ihitang** [comment]
maybe it will be helpful to you

I have operlap2d editor in my git repository (maybe it is not a good idea to hold it there, anyway), from time to time I'm switching between Windows and Mac OS. 

Here's the stacktrace then I tried to open project on my Mac:
> VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
java.lang.IllegalStateException: Provided directory does not exist!
        at com.kotcrab.vis.ui.widget.file.FileChooser.setDirectory(FileChooser.java:821)
        at com.kotcrab.vis.ui.widget.file.FileChooser.setDirectory(FileChooser.java:816)
        at com.uwsoft.editor.view.menu.Overlap2DMenuBarMediator.showOpenProject(Overlap2DMenuBarMediator.java:229)
        at com.uwsoft.editor.view.menu.Overlap2DMenuBarMediator.handleFileMenuNotification(Overlap2DMenuBarMediator.java:148)
        at com.uwsoft.editor.view.menu.Overlap2DMenuBarMediator.handleNotification(Overlap2DMenuBarMediator.java:101)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserver.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacade.java:323)
        at com.uwsoft.editor.event.MenuItemListener.changed(MenuItemListener.java:44)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
        at com.badlogic.gdx.backends.jglfw.JglfwInput$1.touchUp(JglfwInput.java:91)
        at com.badlogic.gdx.InputProcessorQueue.drain(InputProcessorQueue.java:80)
        at com.badlogic.gdx.backends.jglfw.JglfwInput.update(JglfwInput.java:137)
        at com.badlogic.gdx.backends.jglfw.JglfwApplication.frame(JglfwApplication.java:213)
        at com.badlogic.gdx.backends.jglfw.JglfwApplication.start(JglfwApplication.java:198)
        at com.badlogic.gdx.backends.jglfw.JglfwApplication.initialize(JglfwApplication.java:178)
        at com.badlogic.gdx.backends.jglfw.JglfwApplication$1.run(JglfwApplication.java:87)
        at java.lang.Thread.run(Thread.java:745)
