### ISSUE TITLE
Double creating of spriterAnimations

### ISSUE THREAD

**Issue by Pretzel777** [UnderwaterApps/overlap2d#329]
EntityFactory line 299.
`for (int i = 0; i < vo.sSpriterAnimations.size(); i++) {
			Entity child = createEntity(entity, vo.sSpriterAnimations.get(i));
			engine.addEntity(child);
		}`
is duplicated.

**Comment by azakhary** [comment]
Thanks for reporting! this should go to the runtime repo issue tracker though.

**Comment by j3zequiel** [comment]
Great! came here to post same issue. I think it is a editor bug too, because every time i open a project or make a repack, spriter animations are duplicated. If i try to delete them from the scene, editor crashes. Here is the error log:
```
$ java -jar overlap2d-0.1.2.jar
VisUI: Warning, using default favorites preference name for file chooser! (see F
ileChooser.setFavoritesPrefsName(String))
VisUI: Warning, using default favorites preference name for file chooser! (see F
ileChooser.setFavoritesPrefsName(String))
java.lang.NullPointerException
        at com.uwsoft.editor.view.ui.FollowersUIMediator.removeFollower(Follower
sUIMediator.java:193)
        at com.uwsoft.editor.controller.commands.DeleteItemsCommand.doAction(Del
eteItemsCommand.java:68)
        at com.uwsoft.editor.controller.commands.RevertableCommand.callDoAction(
RevertableCommand.java:49)
        at com.uwsoft.editor.controller.commands.EntityModifyRevertableCommand.c
allDoAction(EntityModifyRevertableCommand.java:42)
        at com.uwsoft.editor.controller.commands.RevertableCommand.execute(Rever
tableCommand.java:40)
        at com.puremvc.core.CoreController.executeCommand(CoreController.java:13
9)
        at com.puremvc.patterns.observer.BaseObserver.notifyObserver(BaseObserve
r.java:82)
        at com.puremvc.core.CoreView.notifyObservers(CoreView.java:128)
        at com.puremvc.patterns.facade.SimpleFacade.notifyObservers(SimpleFacade
.java:361)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacad
e.java:323)
        at com.puremvc.patterns.facade.SimpleFacade.sendNotification(SimpleFacad
e.java:350)
        at com.uwsoft.editor.view.stage.tools.SelectionTool.keyDown(SelectionToo
l.java:405)
        at com.uwsoft.editor.view.stage.SandboxMediator$SandboxStageEventListene
r.keyDown(SandboxMediator.java:267)
        at com.uwsoft.editor.view.stage.input.SandboxInputAdapter.keyDown(Sandbo
xInputAdapter.java:38)
        at com.badlogic.gdx.InputMultiplexer.keyDown(InputMultiplexer.java:72)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.j
ava:296)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:23
4)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL con
text found in the current thread.
        at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
        at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
        at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.j
ava:248)
        at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
        at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:
418)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
        at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:114)
        at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:68)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:30
9)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```
Waiting bug fix. 
Thanks

**Comment by Pretzel777** [comment]
Moved that issue to runtime repo issue tracking [#66](https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/issues/66)
