### ISSUE TITLE
BUG editor crush after importing TTF only with uppercase

### ISSUE THREAD

**Issue by postpunkpl** [UnderwaterApps/overlap2d#34]
Hello,

After importing TTF file only with uppercase characters, when you try to put label to scene editor crush with this messages:

log:

com.badlogic.gdx.utils.GdxRuntimeException: No x-height character found in font
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:331)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:153)

**Comment by azakhary** [comment]
can you please share that TTF so I can test it? thanks!

**Comment by postpunkpl** [comment]
the first font from list (Space comics):

http://www.dafont.com/theme.php?cat=102
