### ISSUE TITLE
Crash when dragging animation/sprite into the scene

### ISSUE THREAD

**Issue by GermanCoding** [UnderwaterApps/overlap2d#382]
In the little "preview" on the right side, the animation just looks fine, importing also worked without problems. I'm able to drag the sprite into the scene (which is correctly drawn at first), but when I drop it, the application crashes. Using a console, I managed to extract the following exception:

`java.lang.IndexOutOfBoundsException: index can't be >= size: 0 >= 0
        at com.badlogic.gdx.utils.Array.get(Array.java:127)
        at com.uwsoft.editor.renderer.factory.component.SpriteComponentFactory.createDimensionsComponent(SpriteComponentFactory.java:71)
        at com.uwsoft.editor.renderer.factory.component.ComponentFactory.createCommonComponents(ComponentFactory.java:64)
        at com.uwsoft.editor.renderer.factory.component.SpriteComponentFactory.createComponents(SpriteComponentFactory.java:55)
        at com.uwsoft.editor.renderer.factory.EntityFactory.createEntity(EntityFactory.java:152)
        at com.uwsoft.editor.factory.ItemFactory.createSpriteAnimation(ItemFactory.java:113)
        at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource.drop(DraggableResource.java:86)
        at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource.access$100(DraggableResource.java:36)
        at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource$2.drop(DraggableResource.java:76)
        at com.badlogic.gdx.scenes.scene2d.utils.DragAndDrop$1.dragStop(DragAndDrop.java:138)
        at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchUp(DragListener.java:64)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:316)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.`

(I know it's probably terrible formatted, sorry). From the error it sounds like there is an empty array that should not be empty.

The strange thing: The demo sprite worked. So it has something to do with my own atlas. I created that atlas using GDX's TexturePacker. Later I used the TexturePacker from codeandweb - exactly the same error.

These are my assets:
[character_attack.atlas](http://aknm-craft.de/assets/character_attack.atlas)
[http://aknm-craft.de/assets/character_attack.png](http://aknm-craft.de/assets/character_attack.png)

(I tried a different atlas size, different sprite sizes, POT rule, another names like "attack0001, attack0002"...) nothing of seem seemed to work. Always the same exception.

![character_attack](https://cloud.githubusercontent.com/assets/4279661/14534432/7c2b0302-0269-11e6-9def-4d80e450959b.png)
![attack1](https://cloud.githubusercontent.com/assets/4279661/14534446/8b2d2f9c-0269-11e6-9894-16292e224551.png)
![attack2](https://cloud.githubusercontent.com/assets/4279661/14534445/8b19cc72-0269-11e6-9ce1-cf7df2819d5a.png)
![attack3](https://cloud.githubusercontent.com/assets/4279661/14534448/8b392d1a-0269-11e6-9405-11d788ddc86d.png)
![attack4](https://cloud.githubusercontent.com/assets/4279661/14534447/8b38df5e-0269-11e6-9fdd-7142ab2a94f9.png)
![attack5](https://cloud.githubusercontent.com/assets/4279661/14534449/8b42929c-0269-11e6-92b2-44c389006ae5.png)
![attack6](https://cloud.githubusercontent.com/assets/4279661/14534450/8b514512-0269-11e6-9236-fd5191206a1f.png)
![attack7](https://cloud.githubusercontent.com/assets/4279661/14534451/8b643956-0269-11e6-8cb0-25f5be26c7d7.png)
![attack8](https://cloud.githubusercontent.com/assets/4279661/14534452/8b6846cc-0269-11e6-9c07-6778844c431e.png)
![attack9](https://cloud.githubusercontent.com/assets/4279661/14534453/8b6c6f9a-0269-11e6-89be-70c9255cdd6d.png)
![attack10](https://cloud.githubusercontent.com/assets/4279661/14534454/8b750a42-0269-11e6-8193-bf55940c7bf5.png)

**Comment by GermanCoding** [comment]
Okay, I tried something else today: I **did not** packed the textures, but just imported the raw .png files into Overlay2D, so that Overlay2D creates the atlas for me. But still, the editor crashes when dragging into the scene. It has to be a problem with the textures itself, but I can not figure out what exactly.

**Comment by GermanCoding** [comment]
Ah, I finally found the issue! All three names: Folder name, atlas name and name of the textures have to be exactly the same.
