### ISSUE TITLE
Crashed on add animation

### ISSUE THREAD

**Issue by klolo** [UnderwaterApps/overlap2d#393]
isUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
VisUI: Warning, using default favorites preference name for file chooser! (see FileChooser.setFavoritesPrefsName(String))
java.lang.IndexOutOfBoundsException: index can't be >= size: 0 >= 0
	at com.badlogic.gdx.utils.Array.get(Array.java:127)
	at com.uwsoft.editor.renderer.factory.component.SpriteComponentFactory.createDimensionsComponent(SpriteComponentFactory.java:71)
	at com.uwsoft.editor.renderer.factory.component.ComponentFactory.createCommonComponents(ComponentFactory.java:64)
	at com.uwsoft.editor.renderer.factory.component.SpriteComponentFactory.createComponents(SpriteComponentFactory.java:55)
	at com.uwsoft.editor.renderer.factory.EntityFactory.createEntity(EntityFactory.java:152)
	at com.uwsoft.editor.factory.ItemFactory.createSpriteAnimation(ItemFactory.java:113)
	at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource.drop(DraggableResource.java:86)
	at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource.access$100(DraggableResource.java:36)
	at com.uwsoft.editor.view.ui.box.resourcespanel.draggable.DraggableResource$2.drop(DraggableResource.java:76)
	at com.badlogic.gdx.scenes.scene2d.utils.DragAndDrop$1.dragStop(DragAndDrop.java:138)
	at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchUp(DragListener.java:64)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:316)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:234)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
	at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:114)
	at com.uwsoft.editor.Overlap2D.dispose(Overlap2D.java:68)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by klolo** [comment]
Problem was fixed by changed this line:
SpriteComponentFactory::getRegions
 if(filter.contains(region.name.replaceAll("\\d","")))
was:
region.name.contains(filter)
