### ISSUE TITLE
overlap2d not starting via gradle since last pull

### ISSUE THREAD

**Issue by kutoman** [UnderwaterApps/overlap2d#407]
getting the following error... ist that atlas missing? I couldn't find it in the repository

```
com.badlogic.gdx.utils.GdxRuntimeException: File not found: splash\splash.atlas (Internal)
        at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:103)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216)
        at com.uwsoft.editor.splash.SplashScreen.create(SplashScreen.java:55)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
        at java.awt.Container.addImpl(Container.java:1119)
        at java.awt.Container.add(Container.java:415)
        at com.uwsoft.editor.splash.SplashFrame.addCanvas(SplashFrame.java:137)
        at com.uwsoft.editor.splash.SplashFrame$2.run(SplashFrame.java:98)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
com.badlogic.gdx.utils.GdxRuntimeException: File not found: splash\splash.atlas (Internal)
        at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:103)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216)
        at com.uwsoft.editor.splash.SplashScreen.create(SplashScreen.java:55)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:190)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:88)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at java.awt.Container.addNotify(Container.java:2773)
        at javax.swing.JComponent.addNotify(JComponent.java:4749)
        at javax.swing.JRootPane.addNotify(JRootPane.java:757)
        at java.awt.Container.addNotify(Container.java:2773)
        at java.awt.Window.addNotify(Window.java:770)
        at java.awt.Frame.addNotify(Frame.java:487)
        at java.awt.Window.show(Window.java:1031)
        at java.awt.Component.show(Component.java:1654)
        at java.awt.Component.setVisible(Component.java:1606)
        at java.awt.Window.setVisible(Window.java:1014)
        at com.uwsoft.editor.splash.SplashFrame$2.run(SplashFrame.java:99)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by azakhary** [comment]
It is missing in repository, and is in gitignore, because it should be "auto-generated" upon gradle build task. You need to check why is that not happening. this part is in build.gradle

**Comment by kutoman** [comment]
ok I kinda was expecting this (the generation part) :D.. need to check that

**Comment by kutoman** [comment]
well.. I had to execute the build task explicitly.. I was used to execute run before .. that's why I skipped that generation unintenionally
