### ISSUE TITLE
Crash when randomly clicking the buttons to mirror an image

### ISSUE THREAD

**Issue by nooone** [UnderwaterApps/overlap2d#54]
I was using the 0.0.8a version downloaded from the website.

java.lang.NullPointerException
        at com.uwsoft.editor.gdx.sandbox.ItemSelector.alignSelectionsByX(ItemSelector.java:287)
        at com.uwsoft.editor.gdx.sandbox.ItemSelector.alignSelections(ItemSelector.java:436)
        at com.uwsoft.editor.gdx.ui.UIToolBox$4.touchDown(UIToolBox.java:104)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:55)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:277)
        at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:303)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:231)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$400(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
        at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
        at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
        at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
        at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:172)
        at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:197)
        at com.badlogic.gdx.graphics.g2d.TextureAtlas.dispose(TextureAtlas.java:418)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:389)
        at com.kotcrab.vis.ui.VisUI.dispose(VisUI.java:60)
        at com.uwsoft.editor.gdx.Overlap2D.dispose(Overlap2D.java:73)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:307)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$400(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by azakhary** [comment]
Should be fixed or be different in #75
