### ISSUE TITLE
[Crash Report] Crashes on Start-up.

### ISSUE THREAD

**Issue by tsteinholz** [UnderwaterApps/overlap2d#67]
I believe this happens when ever you launch Overlap2D from your project directory. Well anyways here is the crash log and my system specs.

From overlog.txt:
```
com.badlogic.gdx.utils.GdxRuntimeException: java.util.ConcurrentModificationException
        at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.create(LwjglAWTCanvas.java:222)`
        at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas$1.initGL(LwjglAWTCanvas.java:89)
        at org.lwjgl.opengl.AWTGLCanvas.paint(AWTGLCanvas.java:337)
        at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
        at sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:64)
        at sun.awt.RepaintArea.paint(RepaintArea.java:240)
        at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
        at java.awt.Component.dispatchEventImpl(Component.java:4957)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.uwsoft.editor.renderer.SceneLoader.removeMissingImages(SceneLoader.java:171)
        at com.uwsoft.editor.renderer.SceneLoader.invalidateSceneVO(SceneLoader.java:160)
        at com.uwsoft.editor.renderer.SceneLoader.loadScene(SceneLoader.java:129)
        at com.uwsoft.editor.renderer.SceneLoader.loadScene(SceneLoader.java:151)
        at com.uwsoft.editor.b.c.k.<init>(UIStage.java:45)
        at com.uwsoft.editor.b.b.a.<init>(LevelEditorScreen.java:39)
        at com.uwsoft.editor.b.b.create(LunarEditorListener.java:28)
        at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.create(LwjglAWTCanvas.java:215)
        ... 26 more`
```
System Specs:
```
tsteinholz@Yuri:~/Development/Java/SpaceShooterArtists$ screenfetch
                                     tsteinholz@Yuri
         eeeeeeeeeeeeeeeee           OS: elementary OS 0.3 freya
      eeeeeeeeeeeeeeeeeeeeeee        Kernel: x86_64 Linux 3.16.0-34-generic
    eeeee  eeeeeeeeeeee   eeeee      Uptime: 1d 16h 29m
  eeee   eeeee       eee     eeee    Packages: 2384
 eeee   eeee          eee     eeee   Shell: bash 4.3.11
eee    eee            eee       eee  Resolution: 1920x1080
eee   eee            eee        eee  WM: Mutter(Gala)
ee    eee           eeee       eeee  WM Theme: elementary
ee    eee         eeeee      eeeeee  GTK Theme: Not Found [GTK2/3]
ee    eee       eeeee      eeeee ee  Icon Theme: Not Found
eee   eeee   eeeeee      eeeee  eee  Font: Not Found
eee    eeeeeeeeee     eeeeee    eee  CPU: Intel Core i7-4770 CPU @ 3.9GHz
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee   GPU: GeForce GTX 650 Ti
  eeeeeeee eeeeeeeeeeee      eeee    RAM: 10937MB / 15986MB
    eeeee                 eeeee     
      eeeeeee         eeeeeee       
         eeeeeeeeeeeeeeeee          
```
As well as the directory I was launching the app from:
```
tsteinholz@Yuri:~/Development/Java/SpaceShooterArtists$ ls
assets      export   Overlap2D.jar  project.dt   README.md
config.pit  LICENSE  overlog.txt    project.pit  scenes
```

**Comment by azakhary** [comment]
Does this still happen after #75 ?

**Comment by azakhary** [comment]
Closing it for now.
