### ISSUE TITLE
Project corruption after crash.

### ISSUE THREAD

**Issue by dcman** [UnderwaterApps/overlap2d#70]
After trying to import a sprite animation the editor crashed. I can not reload the project I was working on.
java.lang.ArrayIndexOutOfBoundsException: 32
	at com.uwsoft.editor.renderer.actor.SpriteAnimation.initSpriteAnimation(SpriteAnimation.java:105)
	at com.uwsoft.editor.renderer.actor.SpriteAnimation.<init>(SpriteAnimation.java:78)
	at com.uwsoft.editor.b.d.f.r.<init>(SpriteAnimationThumbnailBox.java:30)
	at com.uwsoft.editor.b.d.a.<init>(AssetList.java:79)
	at com.uwsoft.editor.b.d.aa.d(UILibraryBox.java:33)
	at com.uwsoft.editor.b.c.k.c(UIStage.java:108)
	at com.uwsoft.editor.b.d.b.x.e(DlgNewProject.java:118)
	at com.uwsoft.editor.b.d.b.x.b(DlgNewProject.java:17)
	at com.uwsoft.editor.b.d.b.aa.touchUp(DlgNewProject.java:82)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.jglfw.JglfwInput$1.touchUp(JglfwInput.java:92)
	at com.badlogic.gdx.InputProcessorQueue.drain(InputProcessorQueue.java:80)
	at com.badlogic.gdx.backends.jglfw.JglfwInput.update(JglfwInput.java:138)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication.frame(JglfwApplication.java:212)
	at com.badlogic.gdx.backends.jglfw.JglfwApplication$3.run(JglfwApplication.java:188)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by azakhary** [comment]
This might not happen anymore since #75 
(old project will remain corrupt though)
