### ISSUE TITLE
Field not found: libraryItems

### ISSUE THREAD

**Issue by EdwardAngeles** [UnderwaterApps/overlap2d#85]
I just tried to create a SceneLoader and I got this error:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Field not found: libraryItems (com.uwsoft.editor.renderer.data.ProjectInfoVO)
	at com.badlogic.gdx.utils.Json.readFields(Json.java:776)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:902)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:714)
	at com.uwsoft.editor.renderer.resources.ResourceManager.loadProjectVO(ResourceManager.java:334)
	at com.uwsoft.editor.renderer.resources.ResourceManager.initAllResources(ResourceManager.java:86)
	at com.uwsoft.editor.renderer.SceneLoader.<init>(SceneLoader.java:47)
	at com.angega.testoverlap2d.MyGdxGame.create(MyGdxGame.java:13)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

__I checked the file "project.dt" and the field is there.__

**Comment by azakhary** [comment]
Hi Edward. I assume you are using a file saved by new editor with the old runtime. There is no official NEW runtime at the moment. 

Please take a look again at the part that is mark with "Important" http://overlap2d.com/contributing-to-overlap2d-editor/

New editor is not released yet and is there ofr testing only, if yo plan to work on a project please use old editor and the old runtime, till we release the new runtime.

Thanks!

**Comment by App-Teck** [comment]
I have same problem now, what to do  ? thanks
